
const Articles = [
    {
    id: 1,
    image: "../../../src/Assets/Image1.jpg",
    title: "Dog article 1",
    subtitle: "Dogs",
    text: "Fun article about Hasky dogs",
    read: "UUUUUU",
    },
    {
    id: 2,
    image: "../../../src/Assets/Image2.jpg",
    title: "Castle article 1",
    subtitle: "Castels",
    text: "Fun article about Castle",
    read: "UUUUUU",
    },
    {
    id: 3,
    image: "../../../src/Assets/Image3.jpg",
    title: "Building article 1",
    subtitle: "Other",
    text: "Fun article about buidlings",
    read: "UUUUUU",
    },
    {
    id: 4,
    image: "../../../src/Assets/Image4.jfif",
    title: "Museum article 1",
    subtitle: "Museums",
    text: "Fun article about .....",
    read: "UUUUUU",
    },
    {
    id: 5,
    image: "../../../src/Assets/Image5.jfif",
    title: "Dog article 2",
    subtitle: "Dogs",
    text: "Fun article about ....",
    read: "UUUUUU",
    },
    {
    id: 6,
    image: "../../../src/Assets/Image6.jpg",
    title: "Museum article 2",
    subtitle: "Museums",
    text: "Fun article about .....",
    read: "UUUUUU",
    },
    {
    id: 7,
    image: "../../../src/Assets/Image7.jfif",
    title: "Castles article 2",
    subtitle: "Castles",
    text: "Fun article about .....",
    read: "UUUUUU",
    },
    {
    id: 8,
    image: "../../../src/Assets/Image8.jfif",
    title: "Seaside",
    subtitle: "Other",
    text: "Fun article about .....",
    read: "UUUUUU",
    },
    ]